Texture2D<float4> InputTexture : register(t0);
RWTexture2D<float> OutputTexture : register(u0);

// --- New Bindings for the Line Analysis passes ---
// The pre-calculated Luma texture generated by the first pass becomes the input here
Texture2D<float> LumaInputTexture : register(t1);
RWStructuredBuffer<uint> LineActiveFlags : register(u1);

// --- Weights ---
static const float3 LumaWeights709 = float3(0.2126, 0.7152, 0.0722);
static const float3 LumaWeights2020 = float3(0.2627, 0.6780, 0.0593);

// --- Constant Buffer for Detection Thresholds ---
cbuffer DetectionParams : register(b0)
{
    uint Width;
    uint Height;
    float BlackThreshold;
    float BlackRatio;
    float VarianceThreshold;
};

// --- Helpers ---
// PQ to Linear (for HDR10)
float3 ApplyPQDecode(float3 v)
{
    const float m1 = 0.1593017578125, m2 = 78.84375;
    const float c1 = 0.8359375, c2 = 18.8515625, c3 = 18.6875;
    float3 v_pow = pow(max(v, 0.00001), 1.0 / m2);
    return pow(max(v_pow - c1, 0.0) / (c2 - c3 * v_pow), 1.0 / m1);
}

// sRGB/Gamma to Linear (for all SDR: 8-bit or 10-bit)
float3 ApplySDRLinear(float3 srgb)
{
    return pow(max(srgb, 0.0), 2.2);
}

// --- Phase 1 Entry Points: Luma Conversion ---

// 1. SDR Entry Point (Handles B8G8R8A8 AND R10G10B10A2_SDR)
[numthreads(16, 16, 1)]
void mainSDR(uint3 id : SV_DispatchThreadID)
{
    uint2 size;
    InputTexture.GetDimensions(size.x, size.y);
    if (any(id.xy >= size))
        return;

    float4 color = InputTexture.Load(int3(id.xy, 0));
    float3 linearColor = ApplySDRLinear(color.rgb);
    
    OutputTexture[id.xy] = saturate(dot(linearColor, LumaWeights709));
}

// 2. HDR10 Entry Point (R10G10B10A2 + PQ + BT.2020)
[numthreads(16, 16, 1)]
void mainHDR10(uint3 id : SV_DispatchThreadID)
{
    uint2 size;
    InputTexture.GetDimensions(size.x, size.y);
    if (any(id.xy >= size))
        return;

    float4 color = InputTexture.Load(int3(id.xy, 0));
    float3 linearColor = ApplyPQDecode(saturate(color.rgb));
    
    float luma = dot(linearColor, LumaWeights2020);
    OutputTexture[id.xy] = saturate(luma * 10.0);
}

// 3. scRGB Entry Point (R16G16B16A16 + Linear + BT.709)
[numthreads(16, 16, 1)]
void mainSCRGB(uint3 id : SV_DispatchThreadID)
{
    uint2 size;
    InputTexture.GetDimensions(size.x, size.y);
    if (any(id.xy >= size))
        return;

    float4 linearColor = InputTexture.Load(int3(id.xy, 0));
    float luma = dot(linearColor.rgb, LumaWeights709);
    
    OutputTexture[id.xy] = saturate(luma);
}

// --- Phase 2 Entry Points: Single-Thread-Per-Line Scanners ---

// 4. Horizontal Row Scanner (Top/Bottom Bar Detection)
[numthreads(64, 1, 1)]
void CSRowAnalysis(uint3 id : SV_DispatchThreadID)
{
    uint y = id.x; // Thread global ID maps directly to Row Y
    if (y >= Height)
        return;

    uint darkCount = 0;
    float sum = 0.0f;
    float sumSq = 0.0f;

    // This single thread loops across the full width of the luma texture
    for (uint x = 0; x < Width; ++x)
    {
        float luma = LumaInputTexture.Load(int3(x, y, 0));

        if (luma <= BlackThreshold)
        {
            darkCount++;
            sum += luma;
            sumSq += luma * luma;
        }
    }

    // Mathematical Evaluations
    if (darkCount == 0)
    {
        LineActiveFlags[y] = 1; // Zero dark pixels = definitely video content
        return;
    }

    float darkRatio = (float) darkCount / (float) Width;
    if (darkRatio < BlackRatio)
    {
        LineActiveFlags[y] = 1; // Below threshold = active content
        return;
    }

    float n = (float) darkCount;
    float mean = sum / n;
    float variance = (sumSq / n) - (mean * mean);

    // If variance is above threshold, it's a dynamic image frame, not a static bar
    LineActiveFlags[y] = (variance > VarianceThreshold) ? 1 : 0;
}

// 5. Vertical Column Scanner (Left/Right Bar Detection)
[numthreads(64, 1, 1)]
void CSColAnalysis(uint3 id : SV_DispatchThreadID)
{
    uint x = id.x; // Thread global ID maps directly to Column X
    if (x >= Width)
        return;

    uint darkCount = 0;
    float sum = 0.0f;
    float sumSq = 0.0f;

    // This single thread loops down the full height of the luma texture
    for (uint y = 0; y < Height; ++y)
    {
        float luma = LumaInputTexture.Load(int3(x, y, 0));

        if (luma <= BlackThreshold)
        {
            darkCount++;
            sum += luma;
            sumSq += luma * luma;
        }
    }

    if (darkCount == 0)
    {
        LineActiveFlags[x] = 1;
        return;
    }

    float darkRatio = (float) darkCount / (float) Height;
    if (darkRatio < BlackRatio)
    {
        LineActiveFlags[x] = 1;
        return;
    }

    float n = (float) darkCount;
    float mean = sum / n;
    float variance = (sumSq / n) - (mean * mean);

    LineActiveFlags[x] = (variance > VarianceThreshold) ? 1 : 0;
}
